# -*- coding: utf-8 -*-
"""DLP_LAB6_310552054_林子恒.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1forya1fOsoWEx01XpNKA71tFs8p94ePk
"""

!python -V
!nvcc --version
!nvidia-smi

import string
import os
import time
import math
import random
import gdown
!pip install box2d

!ls
!gdown --id '1yXCz4FdUhTqMkpyaHGU_qH_VEMGbcdt5' --output ddpg-example.py
!gdown --id '1HkY1CUiTXdNl0kQX5jVsOoStpZtMT6p_' --output dqn-example.py

from google.colab import drive
drive.mount('/content/drive')
file_path = "drive/MyDrive/NYCU/109 Summer Deep Learning and Practice/assignment/[Lab6] DQN & DDPG/"

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard
from tensorboard import notebook
notebook.list() # View open TensorBoard instances
# Control TensorBoard display. If no port is provided, 
# the most recently launched TensorBoard is used
'''notebook.display(port=6006, height=800)

notebook.display(port=6007, height=800)'''

# %tensorboard --logdir "drive/MyDrive/NYCU/109 Summer Deep Learning and Practice/assignment/[Lab6] DQN & DDPG/log/"